using System;
using System.Windows.Forms;

namespace NSUNS4_Character_Manager
{
	internal static class Program
	{
		[STAThread]
		private static void Main()
		{
			Application.EnableVisualStyles();
			Application.SetCompatibleTextRenderingDefault(defaultValue: false);
			Application.Run(new Main());
		}

        public static string[] HITEFF =
        {
            "0x00 = None",
            "0x01 = Kick",
            "0x02 = Punch",
            "0x03 = Air",
            "0x04 = Sword",
            "0x05 = Sword Slash",
            "0x06 = Fangs",
            "0x07 = ???",
            "0x08 = ???",
            "0x09 = Fire",
        };

        public static string[] DMGCOND =
        {
            "0x00 = None",
            "0x01 = Unguardable",
            "0x02 = ???",
            "0x03 = Unreboundable",
            "0x04 = ???",
            "0x05 = Extended stagger(STAGGER_NORMAL)",
        };

        public static string[] COND =
        {
            "0x00 = No condition",
            "0x01 = No condition",
            "0x02 = If enemy is on the ground",
            "0x03 = If enemy is on air",
            "0x04 = If previous attack hit (normal characters)",
            "0x05 = No condition",
            "0x06 = No condition",
            "0x07 = No condition",
            "0x08 = No condition",
            "0x09 = No condition",
            "0x0A = No condition",
            "0x0B = No condition",
            "0x0C = If previous attack hit while enemy was guarding",
            "0x0D = ???",
            "0x0E = ???",
            "0x0F = ???",
            "0x10 = If previous attack hit giant character",
            "0x11 = If enemy awakens into giant character",
            "0x12 = ???",
            "0x13 = ???",
            "0x14 = ???",
            "0x17 = ???",
            "0x18 = ???",
            "0x19 = ???",
        };

        public static string[] ME_LIST =
        {
            "ME_SPSKILL_END_MOVE",
            "ME_SPSKILL_END_MOVE2",
            "ME_SPSKILL_START_MOVE_BASE_DEF",
            "ME_SET_SKILL_LOOP_TIME",
            "ME_ENABLE_ATTACK_PRIORITY",
            "ME_DISABLE_ATTACK_PRIORITY",
            "ME_ENABLE_ATTACK_PRIORITY_COMMON",
            "ME_DISABLE_ATTACK_PRIORITY_COMMON",
            "ME_SKILL_DAMAGE_RATE",
            "ME_THROUGH_NORMAL_ATTACK_ON",
            "ME_THROUGH_NORMAL_ATTACK_OFF",
            "ME_KAWARIMI_DISTANCE_SET",
            "ME_KAWARIMI_DISTANCE_RESET",
            "ME_SET_AWAKE_CONDITION",
            "ME_SPSKILL_CUTIN_FRAME",
            "ME_NOT_USE_HIT_STOP",
            "ME_USE_HIT_STOP",
            "ME_SET_DODGE_OFFSET",
            "ME_ADD_CONNECTED_MOTION1",
            "ME_ADD_CONNECTED_MOTION2",
            "ME_ADD_CONNECTED_MOTION3",
            "ME_ENEMY_MOTION_SLOW_START",
            "ME_ENEMY_MOTION_SLOW_END",
            "ME_ENEMY_MOTION_AFTERHIT_SLOW_START",
            "ME_ENEMY_MOTION_AFTERHIT_SLOW_END",
            "ME_SPTYPE_ACT_CANCEL_ON",
            "ME_SPTYPE_ACT_CANCEL_OFF",
            "ME_SKILL_CANCEL_START",
            "ME_SKILL_CANCEL_END",
            "ME_FLOATING_ON",
            "ME_FLOATING_OFF",
            "ME_CIR_ACCEL_SET",
            "ME_JUMPVEL_SET",
            "ME_FWDVELOCITY_SET",
            "ME_FWDVELOCITY_SET_INTERP",
            "ME_CIR_VELOCITY_SET",
            "ME_WARP_AROUND_ENEMY",
            "ME_GRAVITY_SET",
            "ME_VELOCITY_RESET",
            "ME_GRAVITY_RESET",
            "ME_VERTICAL_VELOCITY_RESET",
            "ME_FLIGHT_BEGIN",
            "ME_FLIGHT_END",
            "ME_HOMING_SET",
            "ME_WARP_AROUND_ENEMY_RESERVE",
            "ME_WARP_AROUND_ENEMY_EXEC",
            "ME_ATK_SIDE_MOVE",
            "ME_ATK_AIR_HOMING_ON",
            "ME_ATK_AIR_HOMING_OFF",
            "ME_HOMING_MOVE_BEGIN",
            "ME_HOMING_AIR",
            "ME_COMBO_MOVEFORWARD_INIT_ON",
            "ME_COMBO_MOVEFORWARD_INIT_OFF",
            "ME_CIR_VELOCITY_SET2",
            "ME_ENTRY_EFF_IMPACTLAND",
            "ME_ENTRY_EFF_INOUT_LAND",
            "ME_ENTRY_EFF_CTG",
            "ME_ENTRY_EFF_CTG_SYNC",
            "ME_ENTRY_EFF_CTG_GROUND",
            "ME_ENABLE_DRAW_BODYEFF",
            "ME_DISABLE_DRAW_BODYEFF",
            "ME_DESTROY_EFF",
            "ME_THROW_EFFECT",
            "ME_FOOT_CHAKRA_EFF_ON",
            "ME_FOOT_CHAKRA_EFF_OFF",
            "ME_ENABLE_DRAW_AWAAURA",
            "ME_DISABLE_DRAW_AWAAURA",
            "ME_ENABLE_DRAW_BODYSKILLEFF",
            "ME_DISABLE_DRAW_BODYSKILLEFF",
            "ME_ENABLE_ENEMY_DRAW_AWAAURA",
            "ME_DISABLE_ENEMY_DRAW_AWAAURA",
            "ME_ANMCAMERA_ON",
            "ME_ANMCAMERA_OFF",
            "ME_ANMCAMERA_REVERSE_ON",
            "ME_ANMCAMERA_REVERSE_OFF",
            "ME_SHAKE_CAMERA",
            "ME_SHAKE_CAMERA_VERTICAL",
            "ME_SHAKE_CAMERA_HORIZONTAL",
            "ME_COMBOCAMERA_ON",
            "ME_COMBOCAMERA_OFF",
            "ME_RESET_CAMERA",
            "ME_CAMERA_LOOKAT_SET",
            "ME_CAMERA_LOOKAT_RESET",
            "ME_CORRECT_CAMERA_DIST",
            "ME_CORRECT_CAMERA_DIST_RESET",
            "ME_CHANGE_HUGEAWAKE2_FARCAMERA",
            "ME_CAMERA_LOOKAT_SET_HUGEAWAKE2",
            "ME_SHAKE_CAMERA_NUM",
            "ME_CAMERARESET_CANCEL_BY_SKILL",
            "ME_ATK_HIT_CAM_QUAKE_ON",
            "ME_ATK_HIT_CAM_QUAKE_OFF",
            "ME_BUNSHIN_ENTRY",
            "ME_BUNSHIN_ENTRY_AT_ENEMY",
            "ME_BUNSHIN_POSITION",
            "ME_BUNSHIN_ATKHIT_ON",
            "ME_BUNSHIN_ATKHIT_OFF",
            "ME_AWAKE2_ATKMARKER_ON",
            "ME_AWAKE2_ATKMARKER_OFF",
            "ME_AWAKE2_AIM_ON",
            "ME_AWAKE2_AIM_OFF",
            "ME_AWAKE3_AIMRESET",
            "ME_AWAKE2_AIM_PARAM",
            "ME_AWAKE3_AIM_ADDOBJECT",
            "ME_CHANGE_HUGEAWAKE2_MIDDLECAMERA",
            "ME_CHANGE_HUGEAWAKE2_MIDDLECAMERA_OFF",
            "ME_CHANGE_HUGEAWAKE2_FARCAMERA_OFF",
            "ME_2DNZ_AWAKE2_SUICIDE",
            "ME_2DNZ_AWAKE2_DODGE",
            "ME_2HDN_AWAKE2_R1_ATK_COUNT_SET",
            "ME_2HDN_AWAKE2_R1_SET_CURSE_MARKER",
            "ME_2HNT_AWAKE2_SET_SKILL_COST",
            "ME_AWAKE2_ROT_CTRL_START",
            "ME_AWAKE2_ROT_CTRL_END",
            "ME_AWAKE2_SET_CHAKRA_DRAIN",
            "ME_SET_AWAKE2_CONDITION",
            "ME_1P2P_DIST_CHECK",
            "ME_3HSM_AWAKE2_ENTRY_WOODDRAGON",
            "ME_3GAR_AWAKE2_L1_AGRD_COUNT_SET",
            "ME_DOWN_LOOP_ENEMY",
            "ME_ACT_FALL",
            "ME_ENEMY_SET_ACTION",
            "ME_ADD_CONDITION_PARAM",
            "ME_DAMAGE_TO_YOURSELF",
            "ME_DOWN_ENEMY_AT_FOOTPOS",
            "ME_ENEMY_MOVE_SELF",
            "ME_ENEMY_MOVE_ENEMY_FOOTPOS",
            "ME_MOVE_CORRECT_T0_POS",
            "ME_SET_ENEMY_POS_DIRC_BY_ANM",
            "ME_ENEMY_MOVE_SELF_COORD",
            "ME_ATK_HIT_HEIGHT",
            "ME_DAMAGE_VALUE_SET",
            "ME_DAMAGE_VALUE_SET_SPSKILL",
            "ME_COMBO_DIRECTION_BEGIN",
            "ME_COMBO_DIRECTION_BEGIN_NOLOCK",
            "ME_COMBO_DIRECTION_END",
            "ME_ATK_HOMING_ON",
            "ME_ATK_HOMING_OFF",
            "ME_ATK_HOMING_ALLRANGE",
            "ME_DAMAGE_SET_DIRECT",
            "ME_DAMAGE_SET_DIRECT_BOTH",
            "ME_ADD_COMBO_COUNTER",
            "ME_SE_ON_CTG",
            "ME_SE_ON_ID",
            "ME_THROW_VOICE1",
            "ME_VOICE",
            "ME_VOICE_ON_ID",
            "ME_VOICE_ON_ID_NO_AWAKE_ONLY",
            "ME_VOICE_ON_ID_AWAKE_ONLY",
            "ME_DISABLE_ATTACK_VOICE",
            "ME_DISABLE_COMBO_LAST_SE",
            "ME_SET_CAPTION",
            "ME_JOIN_SUPPORT_START",
            "ME_JOIN_SUPPORT_END",
            "ME_PAD_VIBRATION",
            "ME_ENTRY_DUMMY_SKILL_N",
            "ME_ENTRY_DUMMY_SKILL_N_SYNC",
            "ME_ENEMY_CTRL_ON",
            "ME_ENEMY_CTRL_OFF",
            "ME_STIFF_SET",
            "ME_ANM_SPEED_SET",
            "ME_ENTRY_PROJECTILE",
            "ME_ENTRY_CHAKRA_PROJECTILE",
            "ME_ENTRY_ITEM",
            "ME_ENTRY_COMBO_SKILL_N",
            "ME_ENTRY_COMBO_SKILL_N_COORD",
            "ME_ENTRY_SKILL_ANY",
            "ME_ENTRY_SKILL_ANY_COORD",
            "ME_SKILL_CMB_ON",
            "ME_SKILL_CMB_OFF",
            "ME_INPUT_CHARGE",
            "ME_PARTNER_ORDER",
            "ME_WIRE_ON",
            "ME_WIRE_OFF",
            "ME_PARTNER_DRAW_OFF",
            "ME_PARTNER_DRAW_ON",
            "ME_PARTNER_REPLACE",
            "ME_BG_DRAW_ON",
            "ME_BG_DRAW_OFF",
            "ME_BG_BRIGHT_SET",
            "ME_BG_BRIGHT_RESET",
            "ME_COLOR_FILTER_ON",
            "ME_COLOR_FILTER_OFF",
            "ME_CHANGE_AWAKE2STAGE",
            "ME_BODHIT_ON",
            "ME_BODHIT_OFF",
            "ME_DMGHIT_ON",
            "ME_DMGHIT_OFF",
            "ME_ATEMI_ON",
            "ME_ATEMI_OFF",
            "ME_LANDHIT_BEGIN",
            "ME_LANDHIT_END",
            "ME_HIT_PRM_CORRECT_START",
            "ME_HIT_PRM_CORRECT_END",
            "ME_CAPCEL_ATKHIT1_ON",
            "ME_CAPCEL_ATKHIT1_OFF",
            "ME_CAPCEL_ATKHIT2_ON",
            "ME_CAPCEL_ATKHIT2_OFF",
            "ME_CAPCEL_ATKHIT_OBJECT",
            "ME_CAPCEL_ATKHIT3_ON",
            "ME_CAPCEL_ATKHIT3_OFF",
            "ME_CAPCEL_ATKHIT4_ON",
            "ME_CAPCEL_ATKHIT4_OFF",
            "ME_CAPCEL_ATKHIT5_ON",
            "ME_CAPCEL_ATKHIT5_OFF",
            "ME_ATKHIT_OFFSET",
            "ME_ATKHIT2_OFFSET",
            "ME_ATKHIT3_OFFSET",
            "ME_ATKHIT4_OFFSET",
            "ME_ATKHIT5_OFFSET",
            "ME_ATKHIT_ON",
            "ME_ATKHIT_OFF",
            "ME_ATKHIT2_ON",
            "ME_ATKHIT2_OFF",
            "ME_ATKHIT3_ON",
            "ME_ATKHIT3_OFF",
            "ME_ATKHIT4_ON",
            "ME_ATKHIT4_OFF",
            "ME_ATKHIT5_ON",
            "ME_ATKHIT5_OFF",
            "ME_ATK_HIT_SIZE",
            "ME_DRAWOBJ_DISABLE",
            "ME_DRAWOBJ_ENABLE",
            "ME_SCALE_CHANGE",
            "ME_GLARE_NORMAL",
            "ME_GLARE_NEAR",
            "ME_GLARE_ANIM",
            "ME_FOG_CHANGE_BEGIN",
            "ME_FOG_CHANGE_COLOR",
            "ME_FOG_CHANGE_RESET",
            "ME_SET_SUBSITUTION_KEY",
            "ME_ADD_HEIGHT_PLAYER",
            "ME_USE_CHANGE_TEXTURE",
            "ME_FACE_SUBSTITUTION_PARAM",
            "ME_ENABLE_AFTER_ATTACH_OBJ",
            "ME_DISABLE_AFTER_ATTACH_OBJ",
            "ME_ENEMY_DISP_ON",
            "ME_ENEMY_DISP_OFF",
            "ME_USE_ANM_LIGHT_DIRC_BEGIN",
            "ME_USE_ANM_LIGHT_DIRC_END",
            "ME_DAMAGEDIRC_SET",
            "ME_DAMAGEDIRC_SET_COORD",
            "ME_DAMAGEDIRC_SET_COORD_REV",
            "ME_DISPDIRC_REVERSE",
            "ME_LOOK_ENEMY",
            "ME_ENEMY_DISPDIRC_REVERSE",
            "ME_LOOK_TARGET_ENEMY",
            "ME_GUDOUBALL_DRAW",
            "ME_GUDOUBALL_DRAW_OFF",
            "ME_GUDOUBALL_DRAW_ALL",
            "ME_GUDOUBALL_DRAW_OFF_ALL",
            "ME_GUDOUBALL_SET_DMY",
            "ME_GUDOUBALL_SET_INTERPOLATION",
            "ME_GUDOUBALL_SET_INTERPOLATION_ALL",
            "ME_MOT_UPGRADE",
            "ME_MOT_UPGRADE_CANCEL",
            "ME_ATKHIT_OFF_INSTANT",
            "ME_ATKHIT_OFFSET_END_ANM_RESET",
            "ME_ATKHIT2_OFFSET_END_ANM_RESET",
            "ME_ATKHIT3_OFFSET_END_ANM_RESET",
            "ME_ATKHIT4_OFFSET_END_ANM_RESET",
            "ME_ATKHIT5_OFFSET_END_ANM_RESET",
            "ME_GUDOUBALL_RATE_RANDOM",
            "ME_GUDOUBALL_MAX_RATE",
            "ME_FINISH_FRONT_DIRECTION",
            "ME_SMASH_HIT_ON",
            "ME_SMASH_HIT_OFF",
            "ME_SMASH_HIT_OFF_INSTANT",
            "ME_SMASH_HIT_OFFSET",
            "ME_CREATE_DECAL",
            "ME_CREATE_DECAL_LOOP",
            "ME_MINI_KTY_SET_DMY",
            "ME_MINI_KTY_SET_INTERPOLATION",
            "ME_MINI_KTY_SET_INTERPOLATION_ALL",
            "ME_MINI_KTY_RATE_RANDOM",
            "ME_MINI_KTY_MAX_RATE",
            "ME_DELETE_SKILL",
            "ME_MOTION_BLUR_ON",
            "ME_MOTION_BLUR_OFF",
            "ME_CROSS_FADE_START",
            "ME_ENTRY_ADD_THNDER_EFF",
            "ME_ENTRY_ADD_WATER_EFF",
            "ME_ENTRY_EFFECT",
            "ME_SINK_ENTRY",
            "ME_SINK_SETPARAM",
            "ME_SINK_TO_FLOAT",
            "ME_SINK_FLOAT_SETSPEED",
            "ME_SET_CAPTION_AND_VOICE",
            "ME_GUDOUBALL_OPACITY_CTRL",
            "ME_FINISH_5TYY_WHISTLE"
        };
    }
}
